Collections:
- Metadata:
    Architecture:
    - CAIN
  Name: CAIN
  Paper:
  - https://aaai.org/ojs/index.php/AAAI/article/view/6693/6547
  README: configs/video_interpolators/cain/README.md
Models:
- Config: configs/video_interpolators/cain/cain_b5_320k_vimeo-triple.py
  In Collection: CAIN
  Metadata:
    Training Data: Others
  Name: cain
  Results:
  - Dataset: Others
    Metrics:
      vimeo-90k-triple:
        PSNR: 34.49
        SSIM: 0.9565
    Task: Video_interpolators
  Weights: https://download.openmmlab.com/mmediting/restorers/real_basicvsr/realbasicvsr_c64b20_1x30x8_lr5e-5_150k_reds_20211104-52f77c2c.pth
